[project]
name = "comfyui-photoshop"
description = "🔹 Powerfull bridge to Photoshop by NimaNzrii"
version = "2.0.49rc2"
license = {file = "LICENSE"}
dependencies = ["msgpack", "aiofiles", "numpy"]

[project.urls]
Repository = "https://github.com/RAFOLIE/comfyui-photoshop-fix"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "nimanzrii"
DisplayName = "comfyui-photoshop"
Icon = "data/comfyIcons/logo.svg"
